#!/bin/bash

# Update /etc/modules-load.d/ads.conf from
# appropriate file for this DSM in /etc/ads-modules.d

modf=/etc/ads-modules.d/$(hostname).conf
if ! [ -f $modf ]; then
    # try lower case
    modf=/etc/ads-modules.d/$(hostname | tr 'A-Z' 'a-z').conf
fi

dest=/etc/modules-load.d
dmodf=$dest/ads.conf

if [ -f $modf ]; then
    [ -d $dest ] || mkdir $dest
    ucf --three-way $modf $dmodf
else
    echo "$modf not found. $dmodf unchanged"
fi

