#!/bin/sh
### BEGIN INIT INFO
# Provides: iptables
# Required-Start: mountkernfs $local_fs
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Set up iptables rules
### END INIT INFO
rules=/etc/network/isfs-iptables.rules
rules2=/etc/network/isfs-iptables-project.rules
rules6=/etc/network/isfs-ip6tables.rules
case "$1" in
 start)
  if [ -f "$rules" ]; then
   /sbin/iptables-restore < "$rules"
   echo "iptables loaded from $rules"
   if [ -f "$rules2" ]; then
     /sbin/iptables-restore --noflush < "$rules2"
     echo "iptables loaded from $rules2"
    fi
  fi
  if [ -f "${rules6}" ]; then
   /sbin/ip6tables-restore < "${rules6}"
   echo "ip6tables loaded from ${rules6}"
  fi
  ;;
esac
exit 0

