#!/bin/sh
### BEGIN INIT INFO
# Provides: iptables
# Required-Start: mountkernfs $local_fs
# Required-Stop: $local_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: Set up iptables rules
### END INIT INFO
rules=/etc/network/isfs-iptables.rules
case "$1" in
 start)
  if [ -f "$rules" ]; then
   /sbin/iptables-restore < "$rules"
   echo "iptables loaded from $rules"
  fi
  ;;
esac
exit 0

